/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SRZ5WvEhmIH
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { AuthLayout } from "./auth-layout";

interface Props {
  onWantsToLogin: () => void;
}
export function ForgotPassword(props: Props) {
  return (
    <AuthLayout title="Reset your password">
      <form className="space-y-4">
        <div>
          <Label htmlFor="email">Email</Label>
          <Input id="email" type="email" />
        </div>
        <Button className="w-full" type="submit">
          Reset Password
        </Button>
      </form>
      <div className="flex items-center justify-between">
        <Button
          variant="ghost"
          className="text-sm font-medium text-gray-900 hover:underline dark:text-gray-50"
          onClick={props.onWantsToLogin}
        >
          Back to Login
        </Button>
      </div>
    </AuthLayout>
  );
}
